name: "Tester"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    name: Build Package
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      NUGET_CERT_REVOCATION_MODE: offline

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup MSBuild 1 (x64)
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: x64
      
    - name: Setup MSBuild 2 (x86)
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: x86
        
    - name: Setup MSBuild 3 (arm64)
      if: always()
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: arm64
        
    - name: Setup MSBuild 4 (default)
      if: always()
      uses: microsoft/setup-msbuild@v1
